if (PATCH_VERSION STREQUAL "")
    EXECUTE_PROCESS(
        COMMAND git rev-parse --short HEAD
        OUTPUT_VARIABLE PATCH_VERSION
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
endif()

CONFIGURE_FILE(${SRC} ${DST} @ONLY)
